---
- name: Installing Mediainfo Package
  package:
     name: "{{ item }}"
     state: present
  with_items:
     - mediainfo
     - exiftool

- name: Installing libav-tools
  package:
     name: "{{ item }}"
     state: present
  with_items:
     - libav-tools
  when: "ansible_distribution_version == '16.04'"
